export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
export const REGISTER_ACTION_SUCCESS = 'REGISTER_ACTION_SUCCESS';
export const LOGIN_ACTION_SUCCESS = 'LOGIN_ACTION_SUCCESS';
export const BUSINESS_CREATION_SUCCESS = 'BUSINESS_CREATION_SUCCESS';
export const GET_BUSINESS_SUCCESS = 'GET_BUSINESS_SUCCESS';
export const UPLOAD_CSV_SUCCESS = 'UPLOAD_CSV_SUCCESS';